UPDATE mdl_cascade_region
SET region = 'TRAVEL RETAIL CENTRAL AND SOUTH AMERICA'
WHERE region = 'TRAVEL RETAIL CENTRAL AND SOUTH AMERICA\r';
UPDATE mdl_reports SET region = 'TRAVEL RETAIL CENTRAL AND SOUTH AMERICA' WHERE region = 'TRAVEL RETAIL CENTRAL AND SOUTH AMERICA\r';